In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0) #maximum of X array longitudinally
y = y/100

In [24]:
def sigmoid (x):return 1/(1 + np.exp(-x))
def derivative_sigmoid(x):x * (1-x)

In [11]:
epoch=5 #Setting training iterations 
lr=0.1 

In [12]:
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer
#weight and bias initialization

In [13]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [14]:
for i in range(epoch):
 #Forward Propogation
 hinp1=np.dot(X,wh)
 hinp=hinp1 + bh
 hlayer_act = sigmoid(hinp)
 outinp1=np.dot(hlayer_act,wout)
 outinp= outinp1+bout
 output = sigmoid(outinp)

In [20]:
EO = y-output
outgrad = derivative_sigmoid(output)
d_output = EO * outgrad
EH = d_output.dot(wout.T)
hiddengrad = derivative_sigmoid(hlayer_act)
d_hiddenlayer = EH * hiddengrad


In [21]:
wout += hlayer_act.T.dot(d_output) *lr # dotproduct ofnextlayererror and currentlayerop
wh += X.T.dot(d_hiddenlayer) *lr

In [22]:
print ("-----------Epoch-", i+1, "Starts----------")
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)
print ("-----------Epoch-", i+1, "Ends----------\n")

-----------Epoch- 5 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.83834298]
 [0.8280398 ]
 [0.83583363]]
-----------Epoch- 5 Ends----------



In [27]:
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.83834298]
 [0.8280398 ]
 [0.83583363]]
