In [4]:
from statistics import Fraction as fr
from statistics import mode
import numpy as np
import math
import scipy
# tuple of positive integer numbers
data1 = (2, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 7)

# tuple of a set of fractional numbers
data3 = (fr(1, 2), fr(1, 2), fr(10, 3), fr(2, 3))
# tuple of a set of negative integers
data4 = (-1, -2, -2, -2, -7, -7, -9)
# tuple of strings
data5 = ("red", "blue", "black", "blue", "black", "black", "brown")
print(mode(data1))
print(mode(data3))
print(mode(data4))
print(mode(data5))

5
1/2
-2
black


In [11]:
from scipy import special
a= special.exp2(2)
print(a)


4.0


In [3]:
b=special.sindg(30)
print(b)

0.49999999999999994


In [4]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])
z=np.concatenate((x,y))
z 

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [5]:
gcd = math.gcd(25, 120)
print(gcd)

5


In [6]:
array1 = np.array([[1, -3, 4], [-1, 3, 0]])
array2 = np.array([[7, 4, -2], [3, 6, 8]])

print ("1st Input array : ", array1)
print ("2nd Input array : ", array2)

out_array = np.add(array1, array2)
print ("output added array : ", out_array)

1st Input array :  [[ 1 -3  4]
 [-1  3  0]]
2nd Input array :  [[ 7  4 -2]
 [ 3  6  8]]
output added array :  [[8 1 2]
 [2 9 8]]


In [7]:
print(math.sqrt(16))

4.0


In [8]:
x = 0.5
print(math.cosh(x))
print(math.sinh(x))
print(math.tanh(x))

1.1276259652063807
0.5210953054937474
0.46211715726000974
